---
- name: Install Netris Operator
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  ignore_errors: false
  vars:
    workspace: /opt/ufo_lab/
    netris_operator_repo: https://github.com/jumpojoy/netris-operator
    netris_operator_branch: extensions
    netris_operator_dir: "{{ workspace }}/netris-operator"
  tasks:
    - name: Ensure target directory
      file:
        path:  "{{ workspace }}"
        state: directory

    - name: Download charts repo
      ansible.builtin.git:
        repo: "{{ netris_operator_repo }}"
        dest: "{{ netris_operator_dir }}"
        version: "{{ netris_operator_branch }}"

    - name: Make lvp chart dependencies
      ansible.builtin.shell:
        cmd: helm dep up
        chdir: "{{ netris_operator_dir }}/deploy/charts/netris-operator/"

    - name: Deploy/upgrade netris controller helm release
      kubernetes.core.helm:
        name: netris-operator
        chart_ref: "{{ netris_operator_dir }}/deploy/charts/netris-operator/"
        release_namespace: netris-operator
        create_namespace: true
        values_files:
          - "{{ workspace }}/netris-simulator/templates/k8s/netris/netris_operator.yaml"
        state: present
        wait: true
        wait_timeout: 300s
